# Usa l'immagine ufficiale e leggerissima di NGINX
FROM nginx:alpine

# Copia il tuo file HTML nella cartella pubblica di NGINX
COPY home-banking.html /usr/share/nginx/html/index.html

# Esponi la porta 80
EXPOSE 80