apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fraud-system-alerts
  namespace: default # Assicurati che corrisponda al namespace dove gira Prometheus
  labels:
    release: atlas-monitoring
spec:
  groups:
  - name: fraud-system-alerts
    rules:
    - alert: HighErrorRate
      expr: sum(rate(http_requests_total{status=~"5.."}[2m])) by (service, namespace) / sum(rate(http_requests_total[2m])) by (service, namespace) > 0.05
      for: 2m
      labels:
        severity: critical
        trigger: agent_sre
      annotations:
        summary: "Tasso di errore elevato su {{ $labels.service }}"

    - alert: HighLatency
      expr: histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket[3m])) by (le, service, namespace)) > 2.0
      for: 2m
      labels:
        severity: warning
        trigger: agent_sre
      annotations:
        summary: "Latenza critica su {{ $labels.service }}"

    - alert: CPUSaturation
      expr: sum(rate(container_cpu_usage_seconds_total{pod!=""}[1m])) by (pod, namespace) / sum(kube_pod_container_resource_limits{resource="cpu"}) by (pod, namespace) > 0.85
      for: 2m
      labels:
        severity: warning
        trigger: agent_sre
      annotations:
        summary: "Saturazione CPU sul pod {{ $labels.pod }}"

    - alert: PodCrashLooping
      expr: label_replace(sum by (pod, namespace) (increase(kube_pod_container_status_restarts_total{namespace="default"}[3m]) > 2.5), "deployment", "$1", "pod", "(.*)-[^-]+-[^-]+")
      for: 2m
      labels:
        severity: critical
        trigger: agent_sre
      annotations:
        summary: "Riavvi multipli sul pod {{ $labels.pod }}"
        description: "Il pod {{ $labels.pod }} ha subito riavvii multipli negli ultimi 3 minuti. Possibile OOMKilled o fallimento del Liveness Probe."