services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/9092' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  api-gateway:
    build: ./gateway
    container_name: banca-gateway
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  transaction-client:
    build: ./client
    container_name: python_traffic_client
    environment:
      - GATEWAY_URL=http://api-gateway:8000/api/v1/transactions
      - SLEEP_TIME=10.0
    depends_on:
      api-gateway:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: unless-stopped

  enrichment-system:
    build: ./enrichment_system
    container_name: enrichment_system
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=raw-transactions
      - KAFKA_ENRICHED_TOPIC=enriched-transactions
      - KAFKA_GROUP_ID=enrichment_system_group
      - PYTHONUNBUFFERED=1
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  scoring-system:
    build:
      context: .
      dockerfile: ./scoring_system/Dockerfile
    container_name: scoring_system
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_ENRICHED_TOPIC=enriched-transactions
      - KAFKA_SCORED_TOPIC=scored-transactions
      - KAFKA_GROUP_ID=scoring_system_group
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_SOCKET_TIMEOUT=1.0
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - REDIS_PROFILE_TTL_SECONDS=86400
      - PYTHONUNBUFFERED=1
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=atlas_db
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d atlas_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.6.1
    container_name: kafka-connect
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster-group"
      CONNECT_CONFIG_STORAGE_TOPIC: "_connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "_connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "_connect-status"
      # --- AGGIUNTE FONDAMENTALI PER SINGOLO NODO KAFKA ---
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      # --- CONVERTITORI AVRO ---
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
    command: >
      bash -c "confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest && /etc/confluent/docker/run"
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_started

  kafka-connect-setup:
    image: curlimages/curl:latest
    container_name: kafka-connect-setup
    depends_on:
      kafka-connect:
        condition: service_started
    volumes:
      - ./sink-connector-config.json:/config.json
    command: >
      sh -c "
        echo 'Attendendo le API REST di Kafka Connect...';
        while [ $$(curl -s -o /dev/null -w %{http_code} http://kafka-connect:8083/connectors) -ne 200 ]; do
          echo 'Kafka Connect non è ancora pronto. Riprovo in 5 secondi...';
          sleep 5;
        done;
        echo 'Kafka Connect è pronto. Registro il connettore...';
        curl -X POST -H 'Content-Type: application/json' --data @/config.json http://kafka-connect:8083/connectors;
        echo '\nSetup del connettore completato con successo!';
      "

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
      kafka:
        condition: service_healthy
