services:
  # 1. IL TUO MICROSERVIZIO
  api-gateway:
    build: .
    container_name: banca-gateway
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      # L'indirizzo di Kafka sulla rete interna di Docker
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

  # 2. IL MESSAGE BROKER (APACHE KAFKA UFFICIALE)
  kafka:
    image: apache/kafka:3.7.0
    container_name: banca-kafka
    ports:
      - "9092:9092"
    environment:
      # Configurazione KRaft (senza Zookeeper) per l'immagine ufficiale Apache
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # Apache Kafka richiede un ID cluster univoco per formattare lo storage KRaft
      CLUSTER_ID: "banca-aemilia-cluster-1"