apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-config
  labels:
    app.kubernetes.io/part-of: fraud-detection
    app.kubernetes.io/component: compute-layer
data:
  KAFKA_BROKER: atlas-kafka.default.svc.cluster.local:9092
  SCHEMA_REGISTRY_URL: http://schema-registry.default.svc.cluster.local:8081/
  REDIS_HOST: atlas-redis-master.default.svc.cluster.local
  REDIS_PORT: "6379"