apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: fraud-detection
    app.kubernetes.io/component: compute-layer
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"
spec:
  ingressClassName: nginx
  rules:
    - host: fraud-api.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: locust-ui-ingress
  labels:
    app.kubernetes.io/name: locust-master-ui
    app.kubernetes.io/part-of: fraud-detection
    app.kubernetes.io/component: compute-layer
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"
spec:
  ingressClassName: nginx
  rules:
    - host: locust.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: locust-master-ui
                port:
                  number: 8089
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlas-guardian-dashboard-ingress
  labels:
    app.kubernetes.io/name: atlas-guardian-agent
    app.kubernetes.io/part-of: atlas-guardian
    app.kubernetes.io/component: dashboard
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: guardian-report.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atlas-guardian-dashboard-service
                port:
                  number: 8501
