apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: default
  labels:
    release: atlas-monitoring
    app.kubernetes.io/name: api-gateway
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s