-- Script per inizializzare il database per il Cold Storage

-- Creiamo la tabella per lo storico delle transazioni
CREATE TABLE transactions_history (
    -- Chiave primaria interna, auto-incrementante
    id SERIAL PRIMARY KEY,

    -- Colonne relazionali per query veloci e indicizzazione
    transaction_id VARCHAR(255) NOT NULL UNIQUE,
    "timestamp" TIMESTAMPTZ NOT NULL,
    risk_score INT,
    risk_level VARCHAR(50),

    -- Colonna documentale per il payload JSON completo
    payload JSONB NOT NULL,

    -- Data di inserimento nel DB per auditing
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indici per ottimizzare le performance delle query

-- Indice standard sul timestamp per query basate sul tempo
CREATE INDEX idx_transactions_history_timestamp ON transactions_history ("timestamp");

-- Indice GIN sulla colonna JSONB per query efficienti sui dati annidati
CREATE INDEX idx_transactions_history_payload_gin ON transactions_history USING GIN (payload);

-- Incident reports stored by the ATLAS SRE Guardian
CREATE TABLE IF NOT EXISTS incident_reports (
    incident_id VARCHAR(255) PRIMARY KEY,
    timestamp_utc TIMESTAMPTZ NOT NULL,
    deployment VARCHAR(255) NOT NULL,
    report_data JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_incident_reports_timestamp_utc
    ON incident_reports (timestamp_utc);

CREATE INDEX IF NOT EXISTS idx_incident_reports_deployment
    ON incident_reports (deployment);

CREATE INDEX IF NOT EXISTS idx_incident_reports_report_data_gin
    ON incident_reports USING GIN (report_data);

-- Trend/meta reports generated by Agent 2
CREATE TABLE IF NOT EXISTS trend_reports (
    trend_id VARCHAR(255) PRIMARY KEY,
    generated_at_utc TIMESTAMPTZ NOT NULL,
    deployment VARCHAR(255) NOT NULL,
    report_data JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_trend_reports_generated_at_utc
    ON trend_reports (generated_at_utc);

CREATE INDEX IF NOT EXISTS idx_trend_reports_deployment
    ON trend_reports (deployment);

CREATE INDEX IF NOT EXISTS idx_trend_reports_report_data_gin
    ON trend_reports USING GIN (report_data);
